<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'prototipo',
  'published_date' => '2018-03-15 10:28:46',
  'type' => 'module',
  'version' => 1521109755,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'prototipo',
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/metadata/aos_products_accounts_1MetaData.php',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.prototipo.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.prototipo.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AM_ProjectTemplates/language/es_ES.lang.php',
      'to_module' => 'AM_ProjectTemplates',
      'language' => 'es_ES',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOR_Reports/language/es_ES.lang.php',
      'to_module' => 'AOR_Reports',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/language/es_ES.lang.php',
      'to_module' => 'AOS_Contracts',
      'language' => 'es_ES',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/language/es_ES.lang.php',
      'to_module' => 'AOS_Product_Categories',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/language/es_ES.lang.php',
      'to_module' => 'AOS_Products',
      'language' => 'es_ES',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products_Quotes/language/es_ES.lang.php',
      'to_module' => 'AOS_Products_Quotes',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/language/es_ES.lang.php',
      'to_module' => 'AOS_Quotes',
      'language' => 'es_ES',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bugs/language/es_ES.lang.php',
      'to_module' => 'Bugs',
      'language' => 'es_ES',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Cases/language/es_ES.lang.php',
      'to_module' => 'Cases',
      'language' => 'es_ES',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/language/es_ES.lang.php',
      'to_module' => 'Contacts',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Employees/language/es_ES.lang.php',
      'to_module' => 'Employees',
      'language' => 'es_ES',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Opportunities/language/es_ES.lang.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/language/es_ES.lang.php',
      'to_module' => 'Project',
      'language' => 'es_ES',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/language/es_ES.lang.php',
      'to_module' => 'Users',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'AOR_Reportsaos_product_categories_id_c' => 
    array (
      'id' => 'AOR_Reportsaos_product_categories_id_c',
      'name' => 'aos_product_categories_id_c',
      'label' => 'LBL_CONTRATO_CATEGORIAPRODUCTO_AOS_PRODUCT_CATEGORIES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'AOR_Reports',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-24 04:07:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'AOR_Reportscontrato_categoriaproducto_c' => 
    array (
      'id' => 'AOR_Reportscontrato_categoriaproducto_c',
      'name' => 'contrato_categoriaproducto_c',
      'label' => 'LBL_CONTRATO_CATEGORIAPRODUCTO',
      'comments' => '',
      'help' => '',
      'module' => 'AOR_Reports',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-24 04:07:14',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'AOS_Product_Categories',
      'ext3' => 'aos_product_categories_id_c',
      'ext4' => '',
    ),
    'AOS_Contractsaos_product_categories_id_c' => 
    array (
      'id' => 'AOS_Contractsaos_product_categories_id_c',
      'name' => 'aos_product_categories_id_c',
      'label' => 'LBL_CONTRATO_CATEGORIAPRODUCTO_AOS_PRODUCT_CATEGORIES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'AOS_Contracts',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-24 04:12:27',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'AOS_Contractscontrato_categoriaproducto_c' => 
    array (
      'id' => 'AOS_Contractscontrato_categoriaproducto_c',
      'name' => 'contrato_categoriaproducto_c',
      'label' => 'LBL_CONTRATO_CATEGORIAPRODUCTO',
      'comments' => '',
      'help' => '',
      'module' => 'AOS_Contracts',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-24 04:12:27',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'AOS_Product_Categories',
      'ext3' => 'aos_product_categories_id_c',
      'ext4' => '',
    ),
    'AOS_Contractscontrato_plazo_c' => 
    array (
      'id' => 'AOS_Contractscontrato_plazo_c',
      'name' => 'contrato_plazo_c',
      'label' => 'LBL_CONTRATO_PLAZO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Contracts',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-24 04:27:54',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Contractsfrecuencia_pago_c' => 
    array (
      'id' => 'AOS_Contractsfrecuencia_pago_c',
      'name' => 'frecuencia_pago_c',
      'label' => 'LBL_FRECUENCIA_PAGO',
      'comments' => '',
      'help' => '',
      'module' => 'AOS_Contracts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-23 03:22:46',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'AOS_Contractsmonto_cuota_c' => 
    array (
      'id' => 'AOS_Contractsmonto_cuota_c',
      'name' => 'monto_cuota_c',
      'label' => 'LBL_MONTO_CUOTA',
      'comments' => '',
      'help' => '',
      'module' => 'AOS_Contracts',
      'type' => 'currency',
      'max_size' => '26',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-23 03:17:05',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'AOS_Product_Categoriescodigo_categoria_c' => 
    array (
      'id' => 'AOS_Product_Categoriescodigo_categoria_c',
      'name' => 'codigo_categoria_c',
      'label' => 'LBL_CODIGO_CATEGORIA',
      'comments' => '',
      'help' => '',
      'module' => 'AOS_Product_Categories',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-18 15:03:47',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'AOS_Productsestado_c' => 
    array (
      'id' => 'AOS_Productsestado_c',
      'name' => 'estado_c',
      'label' => 'LBL_ESTADO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Products',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'Disponible',
      'date_modified' => '2017-11-18 20:36:29',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'producto_estatus_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Productsfecha_reserva_c' => 
    array (
      'id' => 'AOS_Productsfecha_reserva_c',
      'name' => 'fecha_reserva_c',
      'label' => 'LBL_FECHA_RESERVA',
      'comments' => '',
      'help' => '',
      'module' => 'AOS_Products',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-21 17:24:34',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'AOS_Productsmetraje_c' => 
    array (
      'id' => 'AOS_Productsmetraje_c',
      'name' => 'metraje_c',
      'label' => 'LBL_METRAJE',
      'comments' => '',
      'help' => '',
      'module' => 'AOS_Products',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-18 17:20:54',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Bugsaccount_id_c' => 
    array (
      'id' => 'Bugsaccount_id_c',
      'name' => 'account_id_c',
      'label' => 'LBL_INCIDENCIAS_CUENTAS_ACCOUNT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Bugs',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 03:49:06',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Bugsaos_products_id_c' => 
    array (
      'id' => 'Bugsaos_products_id_c',
      'name' => 'aos_products_id_c',
      'label' => 'LBL_INCIDENCIA_NUMERODEPARTE_AOS_PRODUCTS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Bugs',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 04:16:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Bugsaos_product_categories_id_c' => 
    array (
      'id' => 'Bugsaos_product_categories_id_c',
      'name' => 'aos_product_categories_id_c',
      'label' => 'LBL_INCIDENCIA_CATEGORIAPRODUCTO_AOS_PRODUCT_CATEGORIES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Bugs',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 04:04:49',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Bugscontact_id_c' => 
    array (
      'id' => 'Bugscontact_id_c',
      'name' => 'contact_id_c',
      'label' => 'LBL_INCIDENCIA_CONTACTO_CONTACT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Bugs',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 04:25:00',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Bugsincidencias_cuentas_c' => 
    array (
      'id' => 'Bugsincidencias_cuentas_c',
      'name' => 'incidencias_cuentas_c',
      'label' => 'LBL_INCIDENCIAS_CUENTAS',
      'comments' => '',
      'help' => '',
      'module' => 'Bugs',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 03:49:06',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Accounts',
      'ext3' => 'account_id_c',
      'ext4' => '',
    ),
    'Bugsincidencia_categoriaproducto_c' => 
    array (
      'id' => 'Bugsincidencia_categoriaproducto_c',
      'name' => 'incidencia_categoriaproducto_c',
      'label' => 'LBL_INCIDENCIA_CATEGORIAPRODUCTO',
      'comments' => '',
      'help' => '',
      'module' => 'Bugs',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 04:04:49',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'AOS_Product_Categories',
      'ext3' => 'aos_product_categories_id_c',
      'ext4' => '',
    ),
    'Bugsincidencia_contacto_c' => 
    array (
      'id' => 'Bugsincidencia_contacto_c',
      'name' => 'incidencia_contacto_c',
      'label' => 'LBL_INCIDENCIA_CONTACTO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Bugs',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 04:25:53',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => 'Contacts',
      'ext3' => 'contact_id_c',
      'ext4' => NULL,
    ),
    'Bugsincidencia_numerodeparte_c' => 
    array (
      'id' => 'Bugsincidencia_numerodeparte_c',
      'name' => 'incidencia_numerodeparte_c',
      'label' => 'LBL_INCIDENCIA_NUMERODEPARTE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Bugs',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 04:21:07',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => 'AOS_Products',
      'ext3' => 'aos_products_id_c',
      'ext4' => NULL,
    ),
    'Casesaos_product_categories_id_c' => 
    array (
      'id' => 'Casesaos_product_categories_id_c',
      'name' => 'aos_product_categories_id_c',
      'label' => 'LBL_CASOS_CATEGORIAPRODUCTO_AOS_PRODUCT_CATEGORIES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Cases',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 04:48:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Casescasos_categoriaproducto_c' => 
    array (
      'id' => 'Casescasos_categoriaproducto_c',
      'name' => 'casos_categoriaproducto_c',
      'label' => 'LBL_CASOS_CATEGORIAPRODUCTO',
      'comments' => '',
      'help' => '',
      'module' => 'Cases',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 04:48:35',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'AOS_Product_Categories',
      'ext3' => 'aos_product_categories_id_c',
      'ext4' => '',
    ),
    'Casesnombre_banco_c' => 
    array (
      'id' => 'Casesnombre_banco_c',
      'name' => 'nombre_banco_c',
      'label' => 'LBL_NOMBRE_BANCO',
      'comments' => '',
      'help' => '',
      'module' => 'Cases',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-23 04:46:57',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Casesnombre_tramitador_c' => 
    array (
      'id' => 'Casesnombre_tramitador_c',
      'name' => 'nombre_tramitador_c',
      'label' => 'LBL_NOMBRE_TRAMITADOR',
      'comments' => '',
      'help' => '',
      'module' => 'Cases',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-23 04:47:33',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsidentificacion_c' => 
    array (
      'id' => 'Contactsidentificacion_c',
      'name' => 'identificacion_c',
      'label' => 'LBL_IDENTIFICACION',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => NULL,
      'date_modified' => '2017-11-18 18:11:29',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Contactsreleacion_principal_c' => 
    array (
      'id' => 'Contactsreleacion_principal_c',
      'name' => 'releacion_principal_c',
      'label' => 'LBL_RELEACION_PRINCIPAL',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-21 17:09:19',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Opportunitiescodigo_categoria_c' => 
    array (
      'id' => 'Opportunitiescodigo_categoria_c',
      'name' => 'codigo_categoria_c',
      'label' => 'LBL_CODIGO_CATEGORIA',
      'comments' => '',
      'help' => '',
      'module' => 'Opportunities',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-22 18:08:45',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectaos_product_categories_id_c' => 
    array (
      'id' => 'Projectaos_product_categories_id_c',
      'name' => 'aos_product_categories_id_c',
      'label' => 'LBL_PROYECTO_CATEGORIAPRODUCTO_AOS_PRODUCT_CATEGORIES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 16:30:33',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Projectproyecto_categoriaproducto_c' => 
    array (
      'id' => 'Projectproyecto_categoriaproducto_c',
      'name' => 'proyecto_categoriaproducto_c',
      'label' => 'LBL_PROYECTO_CATEGORIAPRODUCTO',
      'comments' => '',
      'help' => '',
      'module' => 'Project',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2017-11-23 16:30:33',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'AOS_Product_Categories',
      'ext3' => 'aos_product_categories_id_c',
      'ext4' => '',
    ),
    'Usersidentificacion_c' => 
    array (
      'id' => 'Usersidentificacion_c',
      'name' => 'identificacion_c',
      'label' => 'LBL_IDENTIFICACION',
      'comments' => '',
      'help' => 'Cuando es una persona Natural, colocar la Cédula.  Si es empresa solicitar el Número de RUC',
      'module' => 'Users',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2017-11-18 18:01:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/SearchFields.php',
      'to' => 'custom/modules/AOS_Contracts/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/SearchFields.php',
      'to' => 'custom/working/modules/AOS_Contracts/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/AOS_Contracts/metadata/detailviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/AOS_Contracts/metadata/detailviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/editviewdefs.php',
      'to' => 'custom/modules/AOS_Contracts/metadata/editviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/AOS_Contracts/metadata/editviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/metadata/SearchFields.php',
      'to' => 'custom/modules/AOS_Product_Categories/metadata/SearchFields.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/metadata/SearchFields.php',
      'to' => 'custom/working/modules/AOS_Product_Categories/metadata/SearchFields.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/metadata/detailviewdefs.php',
      'to' => 'custom/modules/AOS_Product_Categories/metadata/detailviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/AOS_Product_Categories/metadata/detailviewdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/metadata/editviewdefs.php',
      'to' => 'custom/modules/AOS_Product_Categories/metadata/editviewdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/AOS_Product_Categories/metadata/editviewdefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/metadata/listviewdefs.php',
      'to' => 'custom/modules/AOS_Product_Categories/metadata/listviewdefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/metadata/searchdefs.php',
      'to' => 'custom/modules/AOS_Product_Categories/metadata/searchdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Product_Categories/metadata/searchdefs.php',
      'to' => 'custom/working/modules/AOS_Product_Categories/metadata/searchdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/SearchFields.php',
      'to' => 'custom/modules/AOS_Products/metadata/SearchFields.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/SearchFields.php',
      'to' => 'custom/working/modules/AOS_Products/metadata/SearchFields.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/detailviewdefs.php',
      'to' => 'custom/modules/AOS_Products/metadata/detailviewdefs.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/AOS_Products/metadata/detailviewdefs.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/editviewdefs.php',
      'to' => 'custom/modules/AOS_Products/metadata/editviewdefs.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/AOS_Products/metadata/editviewdefs.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/listviewdefs.php',
      'to' => 'custom/modules/AOS_Products/metadata/listviewdefs.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/popupdefs.php',
      'to' => 'custom/modules/AOS_Products/metadata/popupdefs.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/popupdefs.php',
      'to' => 'custom/working/modules/AOS_Products/metadata/popupdefs.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/AOS_Products/metadata/quickcreatedefs.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/AOS_Products/metadata/quickcreatedefs.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/searchdefs.php',
      'to' => 'custom/modules/AOS_Products/metadata/searchdefs.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Products/metadata/searchdefs.php',
      'to' => 'custom/working/modules/AOS_Products/metadata/searchdefs.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/detailviewdefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/detailviewdefs.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/AOS_Quotes/metadata/detailviewdefs.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/editviewdefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/editviewdefs.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/AOS_Quotes/metadata/editviewdefs.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/listviewdefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/listviewdefs.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/quickcreatedefs.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/AOS_Quotes/metadata/quickcreatedefs.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/detailviewdefs.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/detailviewdefs.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/editviewdefs.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/editviewdefs.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/listviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/listviewdefs.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bugs/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Bugs/metadata/detailviewdefs.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bugs/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Bugs/metadata/detailviewdefs.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bugs/metadata/editviewdefs.php',
      'to' => 'custom/modules/Bugs/metadata/editviewdefs.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bugs/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Bugs/metadata/editviewdefs.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bugs/metadata/listviewdefs.php',
      'to' => 'custom/modules/Bugs/metadata/listviewdefs.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bugs/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Bugs/metadata/quickcreatedefs.php',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bugs/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Bugs/metadata/quickcreatedefs.php',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Cases/metadata/editviewdefs.php',
      'to' => 'custom/modules/Cases/metadata/editviewdefs.php',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Cases/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Cases/metadata/editviewdefs.php',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Cases/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Cases/metadata/quickcreatedefs.php',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Cases/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Cases/metadata/quickcreatedefs.php',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/SearchFields.php',
      'to' => 'custom/modules/Contacts/metadata/SearchFields.php',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Contacts/metadata/SearchFields.php',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/dashletviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/dashletviewdefs.php',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/dashletviewdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/dashletviewdefs.php',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/detailviewdefs.php',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/detailviewdefs.php',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/editviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/editviewdefs.php',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/editviewdefs.php',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/listviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/listviewdefs.php',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/searchdefs.php',
      'to' => 'custom/modules/Contacts/metadata/searchdefs.php',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/searchdefs.php',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Employees/metadata/listviewdefs.php',
      'to' => 'custom/modules/Employees/metadata/listviewdefs.php',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Project/metadata/detailviewdefs.php',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Project/metadata/detailviewdefs.php',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/editviewdefs.php',
      'to' => 'custom/modules/Project/metadata/editviewdefs.php',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Project/metadata/editviewdefs.php',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Project/metadata/quickcreatedefs.php',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Project/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Project/metadata/quickcreatedefs.php',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/modules/SecurityGroups/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/SecurityGroups/metadata/quickcreatedefs.php',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/modules/SecurityGroups/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/SecurityGroups/metadata/quickcreatedefs.php',
    ),
    71 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Quotes/Ext/Vardefs/sugarfield_approval_status.php',
      'to' => 'custom/Extension/modules/AOS_Quotes/Ext/Vardefs/sugarfield_approval_status.php',
    ),
    72 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Layoutdefs/notes_accounts_1_Notes.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Layoutdefs/notes_accounts_1_Notes.php',
    ),
    73 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Language/es_ES.customnotes_accounts_1.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Language/es_ES.customnotes_accounts_1.php',
    ),
    74 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Language/en_us.customnotes_accounts_1.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Language/en_us.customnotes_accounts_1.php',
    ),
    75 => 
    array (
      'from' => '<basepath>/Extension/modules/Notes/Ext/Vardefs/notes_accounts_1_Notes.php',
      'to' => 'custom/Extension/modules/Notes/Ext/Vardefs/notes_accounts_1_Notes.php',
    ),
    76 => 
    array (
      'from' => '<basepath>/Extension/modules/Bugs/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
      'to' => 'custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
    ),
    77 => 
    array (
      'from' => '<basepath>/Extension/modules/Bugs/Ext/Vardefs/sugarfield_type.php',
      'to' => 'custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_type.php',
    ),
    78 => 
    array (
      'from' => '<basepath>/Extension/modules/Bugs/Ext/Vardefs/sugarfield_aos_products_id_c.php',
      'to' => 'custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_aos_products_id_c.php',
    ),
    79 => 
    array (
      'from' => '<basepath>/Extension/modules/Bugs/Ext/Vardefs/sugarfield_incidencia_categoriaproducto_c.php',
      'to' => 'custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_incidencia_categoriaproducto_c.php',
    ),
    80 => 
    array (
      'from' => '<basepath>/Extension/modules/Bugs/Ext/Vardefs/sugarfield_account_id_c.php',
      'to' => 'custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_account_id_c.php',
    ),
    81 => 
    array (
      'from' => '<basepath>/Extension/modules/Bugs/Ext/Vardefs/sugarfield_incidencia_numerodeparte_c.php',
      'to' => 'custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_incidencia_numerodeparte_c.php',
    ),
    82 => 
    array (
      'from' => '<basepath>/Extension/modules/Bugs/Ext/Vardefs/sugarfield_incidencia_contacto_c.php',
      'to' => 'custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_incidencia_contacto_c.php',
    ),
    83 => 
    array (
      'from' => '<basepath>/Extension/modules/Bugs/Ext/Vardefs/sugarfield_incidencias_cuentas_c.php',
      'to' => 'custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_incidencias_cuentas_c.php',
    ),
    84 => 
    array (
      'from' => '<basepath>/Extension/modules/Bugs/Ext/Vardefs/sugarfield_contact_id_c.php',
      'to' => 'custom/Extension/modules/Bugs/Ext/Vardefs/sugarfield_contact_id_c.php',
    ),
    85 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Layoutdefs/notes_accounts_1_Accounts.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Layoutdefs/notes_accounts_1_Accounts.php',
    ),
    86 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/es_ES.customnotes_accounts_1.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/es_ES.customnotes_accounts_1.php',
    ),
    87 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/en_us.customaos_products_accounts_1.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/en_us.customaos_products_accounts_1.php',
    ),
    88 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/en_us.customnotes_accounts_1.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/en_us.customnotes_accounts_1.php',
    ),
    89 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/es_ES.customaos_products_accounts_1.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/es_ES.customaos_products_accounts_1.php',
    ),
    90 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/aos_products_accounts_1_Accounts.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/aos_products_accounts_1_Accounts.php',
    ),
    91 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/notes_accounts_1_Accounts.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/notes_accounts_1_Accounts.php',
    ),
    92 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Language/en_us.customaos_products_accounts_1.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Language/en_us.customaos_products_accounts_1.php',
    ),
    93 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Language/es_ES.customaos_products_accounts_1.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Language/es_ES.customaos_products_accounts_1.php',
    ),
    94 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Vardefs/aos_products_accounts_1_AOS_Products.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Vardefs/aos_products_accounts_1_AOS_Products.php',
    ),
    95 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Vardefs/sugarfield_fecha_reserva_c.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Vardefs/sugarfield_fecha_reserva_c.php',
    ),
    96 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Vardefs/sugarfield_estado_c.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Vardefs/sugarfield_estado_c.php',
    ),
    97 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Products/Ext/Vardefs/sugarfield_metraje_c.php',
      'to' => 'custom/Extension/modules/AOS_Products/Ext/Vardefs/sugarfield_metraje_c.php',
    ),
    98 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Product_Categories/Ext/Layoutdefs/_overrideAOS_Product_Categories_subpanel_aos_products.php',
      'to' => 'custom/Extension/modules/AOS_Product_Categories/Ext/Layoutdefs/_overrideAOS_Product_Categories_subpanel_aos_products.php',
    ),
    99 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Product_Categories/Ext/Vardefs/sugarfield_codigo_categoria_c.php',
      'to' => 'custom/Extension/modules/AOS_Product_Categories/Ext/Vardefs/sugarfield_codigo_categoria_c.php',
    ),
    100 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/relationships/aos_products_accounts_1MetaData.php',
      'to' => 'custom/Extension/modules/relationships/relationships/aos_products_accounts_1MetaData.php',
    ),
    101 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/vardefs/aos_products_accounts_1_AOS_Products.php',
      'to' => 'custom/Extension/modules/relationships/vardefs/aos_products_accounts_1_AOS_Products.php',
    ),
    102 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/vardefs/aos_products_accounts_1_Accounts.php',
      'to' => 'custom/Extension/modules/relationships/vardefs/aos_products_accounts_1_Accounts.php',
    ),
    103 => 
    array (
      'from' => '<basepath>/Extension/modules/Opportunities/Ext/Vardefs/sugarfield_sales_stage.php',
      'to' => 'custom/Extension/modules/Opportunities/Ext/Vardefs/sugarfield_sales_stage.php',
    ),
    104 => 
    array (
      'from' => '<basepath>/Extension/modules/Opportunities/Ext/Vardefs/sugarfield_codigo_categoria_c.php',
      'to' => 'custom/Extension/modules/Opportunities/Ext/Vardefs/sugarfield_codigo_categoria_c.php',
    ),
    105 => 
    array (
      'from' => '<basepath>/Extension/modules/Users/Ext/Vardefs/sugarfield_identificacion_c.php',
      'to' => 'custom/Extension/modules/Users/Ext/Vardefs/sugarfield_identificacion_c.php',
    ),
    106 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_status.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_status.php',
    ),
    107 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
    ),
    108 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_frecuencia_pago_c.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_frecuencia_pago_c.php',
    ),
    109 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_contrato_categoriaproducto_c.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_contrato_categoriaproducto_c.php',
    ),
    110 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_monto_cuota_c.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_monto_cuota_c.php',
    ),
    111 => 
    array (
      'from' => '<basepath>/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_contrato_plazo_c.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/sugarfield_contrato_plazo_c.php',
    ),
    112 => 
    array (
      'from' => '<basepath>/Extension/modules/Cases/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
      'to' => 'custom/Extension/modules/Cases/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
    ),
    113 => 
    array (
      'from' => '<basepath>/Extension/modules/Cases/Ext/Vardefs/sugarfield_nombre_tramitador_c.php',
      'to' => 'custom/Extension/modules/Cases/Ext/Vardefs/sugarfield_nombre_tramitador_c.php',
    ),
    114 => 
    array (
      'from' => '<basepath>/Extension/modules/Cases/Ext/Vardefs/sugarfield_casos_categoriaproducto_c.php',
      'to' => 'custom/Extension/modules/Cases/Ext/Vardefs/sugarfield_casos_categoriaproducto_c.php',
    ),
    115 => 
    array (
      'from' => '<basepath>/Extension/modules/Cases/Ext/Vardefs/sugarfield_nombre_banco_c.php',
      'to' => 'custom/Extension/modules/Cases/Ext/Vardefs/sugarfield_nombre_banco_c.php',
    ),
    116 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
    ),
    117 => 
    array (
      'from' => '<basepath>/Extension/modules/Project/Ext/Vardefs/sugarfield_proyecto_categoriaproducto_c.php',
      'to' => 'custom/Extension/modules/Project/Ext/Vardefs/sugarfield_proyecto_categoriaproducto_c.php',
    ),
    118 => 
    array (
      'from' => '<basepath>/Extension/modules/AOR_Reports/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
      'to' => 'custom/Extension/modules/AOR_Reports/Ext/Vardefs/sugarfield_aos_product_categories_id_c.php',
    ),
    119 => 
    array (
      'from' => '<basepath>/Extension/modules/AOR_Reports/Ext/Vardefs/sugarfield_contrato_categoriaproducto_c.php',
      'to' => 'custom/Extension/modules/AOR_Reports/Ext/Vardefs/sugarfield_contrato_categoriaproducto_c.php',
    ),
    120 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_releacion_principal_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_releacion_principal_c.php',
    ),
    121 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/sugarfield_identificacion_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/sugarfield_identificacion_c.php',
    ),
  ),
);